#!/bin/bash
# fastr execution in linux

# point this to java executable (java if JRE/JDK on path)
export JAVA=java
# put this to fastr directory home
export FASTR_HOME=/home/peta/devel/work/fastr

export CP=$FASTR_HOME/bin:$FASTR_HOME/lib/antlr-runtime-3.5.jar:$FASTR_HOME/lib/arpack_combined_all.jar:$FASTR_HOME/lib/junit-4.8.jar:$FASTR_HOME/lib/netlib-java-0.9.3.jar:$FASTR_HOME/lib/truffle-api-03-16-2013.jar
$JAVA -cp $CP r/Console
